### ISSUE TITLE
Could you please provide the training time stats?

### ISSUE THREAD

**Issue by LeenaShekhar** [pltrdy/shared_models#1]
Hello,
Thank you for making the model available. Could you also provide the time and resources it took to train this model if possible?

**Comment by pltrdy** [comment]
Hi,
I used a single GTX 1080. I do not have precise records, but it takes around 2-3 days I guess to get 16 epochs done. Note that such model may not require that much epochs (10 may be ok). 
Also, note that this is just a repository for me to share models. In some cases I may share poorly performing models e.g. when discussing an issue (it was the case for the two first ones). 
I'll share better ones soon (on Gigaword and CNN/DM summarization task)

**Comment by LeenaShekhar** [comment]
I found helpful answers here: http://forum.opennmt.net/t/text-summarization-on-gigaword-and-rouge-scoring/85/6 . I was about to close this issue. Thank you.

**Comment by pltrdy** [comment]
(also to be more precise we discussed issues about summarization here https://github.com/OpenNMT/OpenNMT-py/issues/340)
